version: '3'
services:
  
  backend:
    build:
      context: .
      dockerfile: ./Snappet/Dockerfile
    container_name: Snappet-backend
    ports:
      - 80:80
      - 443:443
  frontend:
    build:
      context: ./web
      dockerfile: ./Dockerfile
    container_name: Snappet-frontend
    ports:
      - 3000:3000